[build]
  functions = "netlify/functions"

  [template.environment]
  MAILCHIMP_API_KEY = "your-mailchimp-api-key"
  MAILCHIMP_SERVER_PREFIX = "your-server-prefix"
  MAILCHIMP_LIST_ID = "your-list-id"
